export const ICONS = {
  backArrow: require('../assets/icons/backArrow.png'),
  rightArrow: require('../assets/icons/rightArrow.png'),
  passportIcon: require('../assets/icons/passport.png'),
  docIcon: require('../assets/icons/document.png'),
  cardIcon: require('../assets/icons/card.png'),
  identityCardIcon: require('../assets/icons/identityCardIcon.png'),
  cameraIcon: require('../assets/icons/camera.png'),
  uploadIcon: require('../assets/icons/upload.png'),
  passportpageIcon: require('../assets/icons/passportPage.png'),
  selfieIcon: require("../assets/icons/selfieIcon.png"),
  gogglesIcon: require("../assets/icons/googlesIcon.png"),
  docuploadicon: require("../assets/icons/documentupload.png"),
  selfieuploadIcon: require("../assets/icons/selfieupload.png"),
  signatureuploadIcon: require("../assets/icons/signatureupload.png"),
  verificationIcon: require("../assets/icons/verification.png"),
  camerabtnIcon: require("../assets/icons/cameraBtn.png"),
  frontpage: require("../assets/icons/frontpage.png"),
  frontpage: require("../assets/icons/frontpage.png"),
  certificate: require("../assets/icons/certificate.png"),
  backpage: require("../assets/icons/backpage.png"),
  succespop: require("../assets/icons/successPop.png"),
  deletepop: require("../assets/icons/deletePop.png"),
  waitingpop: require("../assets/icons/waitingPop.png"),
  bellIcon: require("../assets/icons/bell.png"),
  searchIcon: require("../assets/icons/searchIcon.png"),
  boxIcon: require("../assets/icons/box.png"),
  googleIcon: require("../assets/icons/google.png"),
  officeIcon: require("../assets/icons/office.png"),
  menuIcon: require("../assets/icons/menuBar.png"),
  laptopIcon: require("../assets/icons/laptop.png"),
  androidIcon: require("../assets/icons/android.png"),
  iphoneIcon: require("../assets/icons/iphone.png"),
  dltestIcon: require("../assets/icons/dltest.png"),
  upIcon: require("../assets/icons/up.png"),
  downIcon: require("../assets/icons/down.png"),
  noratingIcon: require("../assets/icons/norating.png"),
  ratingIcon: require("../assets/icons/rating.png"),
  dashPersonalIcon: require('../assets/icons/personal.png'),
  dashcertificateIcon: require('../assets/icons/certificateicon.png'),
  dashfinancialIcon: require('../assets/icons/financial.png'),
  dashemployementIcon: require('../assets/icons/employement.png'),
  eyeIcon: require('../assets/icons/eye.png'),
  activeIcon: require('../assets/icons/activeIcon.png'),
  revokedIcon: require('../assets/icons/revokedIcon.png'),
  suspendedIcon: require('../assets/icons/suspendedIcon.png'),
  unverificationIcon: require('../assets/icons/unverificationIcon.png'),
  plusBtn: require('../assets/icons/plusBtn.png'),
  refreshBtn: require('../assets/icons/refreshBtn.png'),


  pkicertificateIcon: require('../assets/icons/pkicertificate.png'),
  fdi2Icon: require('../assets/icons/fdi2.png'),
  consentIcon: require('../assets/icons/consent.png'),
  otpIcon: require('../assets/icons/otp.png'),
  copyIcon: require('../assets/icons/copy.png'),
  normalSettingIcon: require('../assets/icons/settingnormal.png'),
  paymentsettingIcon: require('../assets/icons/paymentsetting.png'),
  privacysettingIcon: require('../assets/icons/privacy.png'),
  notificationMessage: require('../assets/icons/notimessage.png'),
  notificationAlert: require('../assets/icons/notialert.png'),
  notificationdocId: require('../assets/icons/notiIdcard.png'),

  timeIcon: require('../assets/icons/timeIcon.png'),
  applicationIcon: require('../assets/icons/application.png'),
  userIcon: require('../assets/icons/user.png'),
  actionIcon: require('../assets/icons/action.png'),
  navIcon: require('../assets/icons/navigation.png'),

  plusIcon: require('../assets/icons/plusIcon.png'),
  paypalIcon: require('../assets/icons/paypal.png'),
  appleIcon: require('../assets/icons/appleIcon.png'),
  visaCardIcon: require('../assets/icons/visaCard.png'),
  masterCardIcon: require('../assets/icons/masterCard.png'),
  menudotIcon: require('../assets/icons/menuIcon.png'),

  otpLogoIcon: require('../assets/icons/otpscreenlogo.png'),
  otpVerifyLogo: require('../assets/icons/otpverifiedLogo.png'),

  report_useractive: require('../assets/icons/useractive.png'),
  report_userclickevents: require('../assets/icons/userclicks.png'),
  report_userpurchases: require('../assets/icons/userpurchases.png'),
  report_userlikes: require('../assets/icons/userlikes.png'),
  report_menu: require('../assets/icons/horizontalMenu.png'),
  profileEdit: require('../assets/icons/profileEdit.png'),
  loaderimage: require('../assets/icons/loaderImage.png'),
  lightning: require('../assets/icons/lightning.png'),

  suspendIcon: require('../assets/icons/suspendCard.png'),
  waitingMsg: require('../assets/icons/waitingMsg.png'),
  successBig: require('../assets/icons/successBig.png'),
  errorIcon: require('../assets/icons/error.png'),

  frontPageicon: require('../assets/icons/frontPageicon.png'),
  backpageicon: require('../assets/icons/backpageicon.png'),
  qrcodepage: require('../assets/icons/qrcodepage.png'),
  biographic: require('../assets/icons/biographic.png'),
  identityHome: require('../assets/icons/identityHome.png'),
  autenticationIcn: require('../assets/icons/autenticationIcn.png'),
  consentIcon: require('../assets/icons/consentIcon.png'),
  reportIconHome: require('../assets/icons/reportIconHome.png'),


















  













  drawerhome: require('../assets/icons/drawer/home.png'),
  drawerapplication: require('../assets/icons/drawer/application.png'),
  draweridentity: require('../assets/icons/drawer/identity.png'),
  drawermanageidentity: require('../assets/icons/drawer/manageidentity.png'),
  drawerprofile: require('../assets/icons/drawer/account.png'),
  draweraccount: require('../assets/icons/drawer/setting.png'),
  drawerfeedback: require('../assets/icons/drawer/feedback.png'),






};
export const IMAGES = {
  background: require('../assets/images/background.png'),
  impovedLogo: require("../assets/images/improvedLogo.png"),
  centerLogo: require("../assets/images/centerImage.png"),
  animation: require("../assets/images/animation.png"),
  centerrGroup: require("../assets/images/centerGroup.png"),
  profileimage: require('../assets/images/profilkeimage.png'),
  dlimage: require('../assets/images/DLImage.png'),
  impovedColorLogo: require("../assets/images/improvedColor.png"),
  dlVertical: require('../assets/images/dlVertical.png'),
  backHorizontal: require('../assets/images/backHorizontal.png'),
  qrimageBig: require('../assets/images/qrimageBig.png'),




};
export const COUNTRYIMAGES = {
   AD : require('../assets/images/country/AD.png'),
   AE : require('../assets/images/country/AE.png'),
   AF : require('../assets/images/country/AF.png'),
   AG : require('../assets/images/country/AG.png'),
   AI : require('../assets/images/country/AI.png'),
   AL : require('../assets/images/country/AL.png'),
   AM : require('../assets/images/country/AM.png'),
   AO : require('../assets/images/country/AO.png'),
   AR : require('../assets/images/country/AR.png'),
   AS : require('../assets/images/country/AS.png'),
   AT : require('../assets/images/country/AT.png'),
   AU : require('../assets/images/country/AU.png'),
   AW : require('../assets/images/country/AW.png'),
   AX : require('../assets/images/country/AX.png'),
   AZ : require('../assets/images/country/AZ.png'),
   BA : require('../assets/images/country/BA.png'),
   BB : require('../assets/images/country/BB.png'),
   BD : require('../assets/images/country/BD.png'),
   BE : require('../assets/images/country/BE.png'),
   BF : require('../assets/images/country/BF.png'),
   BG : require('../assets/images/country/BG.png'),
   BH : require('../assets/images/country/BH.png'),
   BI : require('../assets/images/country/BI.png'),
   BJ : require('../assets/images/country/BJ.png'),
   BL : require('../assets/images/country/BL.png'),
   BM : require('../assets/images/country/BM.png'),
   BN : require('../assets/images/country/BN.png'),
   BO : require('../assets/images/country/BO.png'),
   BR : require('../assets/images/country/BR.png'),
   BS : require('../assets/images/country/BS.png'),
   BT : require('../assets/images/country/BT.png'),
   BV : require('../assets/images/country/BV.png'),
   BW : require('../assets/images/country/BW.png'),
   BY : require('../assets/images/country/BY.png'),
   BZ : require('../assets/images/country/BZ.png'),
   CA : require('../assets/images/country/CA.png'),
   CC : require('../assets/images/country/CC.png'),
   CD : require('../assets/images/country/CD.png'),
   CF : require('../assets/images/country/CF.png'),
   CG : require('../assets/images/country/CG.png'),
   CH : require('../assets/images/country/CH.png'),
   CI : require('../assets/images/country/CI.png'),
   CK : require('../assets/images/country/CK.png'),
   CL : require('../assets/images/country/CL.png'),
   CM : require('../assets/images/country/CM.png'),
   CN : require('../assets/images/country/CN.png'),
   CO : require('../assets/images/country/CO.png'),
   CR : require('../assets/images/country/CR.png'),
   CU : require('../assets/images/country/CU.png'),
   CV : require('../assets/images/country/CV.png'),
   CW : require('../assets/images/country/CW.png'),
   CX : require('../assets/images/country/CX.png'),
   CY : require('../assets/images/country/CY.png'),
   CZ : require('../assets/images/country/CZ.png'),
   DE : require('../assets/images/country/DE.png'),
   DJ : require('../assets/images/country/DJ.png'),
   DK : require('../assets/images/country/DK.png'),
   DM : require('../assets/images/country/DM.png'),
   DO : require('../assets/images/country/DO.png'),
   DZ : require('../assets/images/country/DZ.png'),
   EC : require('../assets/images/country/EC.png'),
   EE : require('../assets/images/country/EE.png'),
   EG : require('../assets/images/country/EG.png'),
   ER : require('../assets/images/country/ER.png'),
   ES : require('../assets/images/country/ES.png'),
   ET : require('../assets/images/country/ET.png'),
   EU : require('../assets/images/country/EU.png'),
   FI : require('../assets/images/country/FI.png'),
   FJ : require('../assets/images/country/FJ.png'),
   FK : require('../assets/images/country/FK.png'),
   FM : require('../assets/images/country/FM.png'),
   FO : require('../assets/images/country/FO.png'),
   FR : require('../assets/images/country/FR.png'),
   GA : require('../assets/images/country/GA.png'),
   GB : require('../assets/images/country/GB.png'),
   GBENG : require('../assets/images/country/GB-ENG.png'),
   GBNIR : require('../assets/images/country/GB-NIR.png'),
   GBSCT : require('../assets/images/country/GB-SCT.png'),
   GBWLS : require('../assets/images/country/GB-WLS.png'),
   GBZET : require('../assets/images/country/GB-ZET.png'),
   GD : require('../assets/images/country/GD.png'),
   GE : require('../assets/images/country/GE.png'),
   GF : require('../assets/images/country/GF.png'),
   GG : require('../assets/images/country/GG.png'),
   GH : require('../assets/images/country/GH.png'),
   GI : require('../assets/images/country/GI.png'),
   GL : require('../assets/images/country/GL.png'),
   GM : require('../assets/images/country/GM.png'),
   GN : require('../assets/images/country/GN.png'),
   GP : require('../assets/images/country/GP.png'),
   GQ : require('../assets/images/country/GQ.png'),
   GR : require('../assets/images/country/GR.png'),
   GS : require('../assets/images/country/GS.png'),
   GT : require('../assets/images/country/GT.png'),
   GU : require('../assets/images/country/GU.png'),
   GW : require('../assets/images/country/GW.png'),
   GY : require('../assets/images/country/GY.png'),
   HK : require('../assets/images/country/HK.png'),
   HM : require('../assets/images/country/HM.png'),
   HN : require('../assets/images/country/HN.png'),
   HR : require('../assets/images/country/HR.png'),
   HT : require('../assets/images/country/HT.png'),
   HU : require('../assets/images/country/HU.png'),
   ID : require('../assets/images/country/ID.png'),
   IE : require('../assets/images/country/IE.png'),
   IL : require('../assets/images/country/IL.png'),
   IM : require('../assets/images/country/IM.png'),
   IN : require('../assets/images/country/IN.png'),
   IO : require('../assets/images/country/IO.png'),
   IQ : require('../assets/images/country/IQ.png'),
   IR : require('../assets/images/country/IR.png'),
   IS : require('../assets/images/country/IS.png'),
   IT : require('../assets/images/country/IT.png'),
   JE : require('../assets/images/country/JE.png'),
   JM : require('../assets/images/country/JM.png'),
   JO : require('../assets/images/country/JO.png'),
   JP : require('../assets/images/country/JP.png'),
   KE : require('../assets/images/country/KE.png'),
   KG : require('../assets/images/country/KG.png'),
   KH : require('../assets/images/country/KH.png'),
   KI : require('../assets/images/country/KI.png'),
   KM : require('../assets/images/country/KM.png'),
   KN : require('../assets/images/country/KN.png'),
   KP : require('../assets/images/country/KP.png'),
   KR : require('../assets/images/country/KR.png'),
   KW : require('../assets/images/country/KW.png'),
   KY : require('../assets/images/country/KY.png'),
   KZ : require('../assets/images/country/KZ.png'),
   LA : require('../assets/images/country/LA.png'),
   LB : require('../assets/images/country/LB.png'),
   LC : require('../assets/images/country/LC.png'),
   LGBT : require('../assets/images/country/LGBT.png'),
   LI : require('../assets/images/country/LI.png'),
   LK : require('../assets/images/country/LK.png'),
   LR : require('../assets/images/country/LR.png'),
   LS : require('../assets/images/country/LS.png'),
   LT : require('../assets/images/country/LT.png'),
   LU : require('../assets/images/country/LU.png'),
   LV : require('../assets/images/country/LV.png'),
   LY : require('../assets/images/country/LY.png'),
   MA : require('../assets/images/country/MA.png'),
   MC : require('../assets/images/country/MC.png'),
   MD : require('../assets/images/country/MD.png'),
   ME : require('../assets/images/country/ME.png'),
   MF : require('../assets/images/country/MF.png'),
   MG : require('../assets/images/country/MG.png'),
   MH : require('../assets/images/country/MH.png'),
   MK : require('../assets/images/country/MK.png'),
   ML : require('../assets/images/country/ML.png'),
   MM : require('../assets/images/country/MM.png'),
   MN : require('../assets/images/country/MN.png'),
   MO : require('../assets/images/country/MO.png'),
   MP : require('../assets/images/country/MP.png'),
   MQ : require('../assets/images/country/MQ.png'),
   MR : require('../assets/images/country/MR.png'),
   MS : require('../assets/images/country/MS.png'),
   MT : require('../assets/images/country/MT.png'),
   MU : require('../assets/images/country/MU.png'),
   MV : require('../assets/images/country/MV.png'),
   MW : require('../assets/images/country/MW.png'),
   MX : require('../assets/images/country/MX.png'),
   MY : require('../assets/images/country/MY.png'),
   MZ : require('../assets/images/country/MZ.png'),
   NA : require('../assets/images/country/NA.png'),
   NC : require('../assets/images/country/NC.png'),
   NE : require('../assets/images/country/NE.png'),
   NF : require('../assets/images/country/NF.png'),
   NG : require('../assets/images/country/NG.png'),
   NI : require('../assets/images/country/NI.png'),
   NL : require('../assets/images/country/NL.png'),
   NO : require('../assets/images/country/NO.png'),
   NP : require('../assets/images/country/NP.png'),
   NR : require('../assets/images/country/NR.png'),
   NU : require('../assets/images/country/NU.png'),
   NZ : require('../assets/images/country/NZ.png'),
   OM : require('../assets/images/country/OM.png'),
   PA : require('../assets/images/country/PA.png'),
   PE : require('../assets/images/country/PE.png'),
   PF : require('../assets/images/country/PF.png'),
   PG : require('../assets/images/country/PG.png'),
   PH : require('../assets/images/country/PH.png'),
   PK : require('../assets/images/country/PK.png'),
   PL : require('../assets/images/country/PL.png'),
   PM : require('../assets/images/country/PM.png'),
   PN : require('../assets/images/country/PN.png'),
   PR : require('../assets/images/country/PR.png'),
   PS : require('../assets/images/country/PS.png'),
   PT : require('../assets/images/country/PT.png'),
   PW : require('../assets/images/country/PW.png'),
   PY : require('../assets/images/country/PY.png'),
   QA : require('../assets/images/country/QA.png'),
   RE : require('../assets/images/country/RE.png'),
   RO : require('../assets/images/country/RO.png'),
   RS : require('../assets/images/country/RS.png'),
   RU : require('../assets/images/country/RU.png'),
   RW : require('../assets/images/country/RW.png'),
   SA : require('../assets/images/country/SA.png'),
   SB : require('../assets/images/country/SB.png'),
   SC : require('../assets/images/country/SC.png'),
   SD : require('../assets/images/country/SD.png'),
   SE : require('../assets/images/country/SE.png'),
   SG : require('../assets/images/country/SG.png'),
   SH : require('../assets/images/country/SH.png'),
   SI : require('../assets/images/country/SI.png'),
   SJ : require('../assets/images/country/SJ.png'),
   SK : require('../assets/images/country/SK.png'),
   SL : require('../assets/images/country/SL.png'),
   SM : require('../assets/images/country/SM.png'),
   SN : require('../assets/images/country/SN.png'),
   SO : require('../assets/images/country/SO.png'),
   SR : require('../assets/images/country/SR.png'),
   SS : require('../assets/images/country/SS.png'),
   ST : require('../assets/images/country/ST.png'),
   SV : require('../assets/images/country/SV.png'),
   SX : require('../assets/images/country/SX.png'),
   SY : require('../assets/images/country/SY.png'),
   SZ : require('../assets/images/country/SZ.png'),
   TC : require('../assets/images/country/TC.png'),
   TD : require('../assets/images/country/TD.png'),
   TF : require('../assets/images/country/TF.png'),
   TG : require('../assets/images/country/TG.png'),
   TH : require('../assets/images/country/TH.png'),
   TJ : require('../assets/images/country/TJ.png'),
   TK : require('../assets/images/country/TK.png'),
   TL : require('../assets/images/country/TL.png'),
   TM : require('../assets/images/country/TM.png'),
   TN : require('../assets/images/country/TN.png'),
   TO : require('../assets/images/country/TO.png'),
   TR : require('../assets/images/country/TR.png'),
   TT : require('../assets/images/country/TT.png'),
   TV : require('../assets/images/country/TV.png'),
   TW : require('../assets/images/country/TW.png'),
   TZ : require('../assets/images/country/TZ.png'),
   UA : require('../assets/images/country/UA.png'),
   UG : require('../assets/images/country/UG.png'),
   UM : require('../assets/images/country/UM.png'),
   US : require('../assets/images/country/US.png'),
   USCA : require('../assets/images/country/US-CA.png'),
   UY : require('../assets/images/country/UY.png'),
   UZ : require('../assets/images/country/UZ.png'),
   VA : require('../assets/images/country/VA.png'),
   VC : require('../assets/images/country/VC.png'),
   VE : require('../assets/images/country/VE.png'),
   VG : require('../assets/images/country/VG.png'),
   VI : require('../assets/images/country/VI.png'),
   VN : require('../assets/images/country/VN.png'),
   VU : require('../assets/images/country/VU.png'),
   WF : require('../assets/images/country/WF.png'),
   WS : require('../assets/images/country/WS.png'),
   XK : require('../assets/images/country/XK.png'),
   YE : require('../assets/images/country/YE.png'),
   YT : require('../assets/images/country/YT.png'),
   ZA : require('../assets/images/country/ZA.png'),
   ZM : require('../assets/images/country/ZM.png'),
   ZW : require('../assets/images/country/ZW.png'),
};

export const THEME = {
  icons: ICONS,
  assets: IMAGES,
  flags:COUNTRYIMAGES
};
